POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 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

//{
//  "model" : "gpt-3.5-turbo",
//  "messages": [
//    {"role": "user", "content": "안녕하세요? 저는 동물매개팀의 조장 이태권입니다. 반갑습니다.\n이번에 저희는 동물매개라는 주제를 가지고 활동을 했었는데요.\n활동을 하면서 난항을 겪기도 했었고, 많은 어려움들이 있었습니다.\n하지만, 우여곡절 끝에 이렇게 발표를 하게되었고, 두가지의 결과물을 가지고 왔습니다.\n그럼, 지금부터 발표를 시작하겠습니다.\n먼저 지도를 보시겠습니다.\n저희는 서울시,강원도,제주도 이렇게 3개의 시,도를 다녀왔고 총 8군데를 방문하였습니다.\n먼저 강원도부터 보시겠습니다.\n먼저, 강원도입니다. 강원도에서는 1군데만 다녀왔는데요. 준독애견트레이닝 센터라고\n애견트레이닝에대해 알고자 방문하였습니다. 여기 사진에보이는 분이 준독애견트레이닝센터장인\n이준한 대표님이십니다.\n다음으로 서울입니다.\n"},
//    {"role": "system", "content":  "내용에 대해 다음 네 가지 조건을 모두 만족하여 응답해주세요.\n1. 스크립트를 문맥에 맞게 수정하기\n2. 문맥을 수정한 스크립트에서 중요한 정보만을 요약하기\n3. 요약된 내용이 한국어가 아니라면 한국어로 번역하기\n4. 내용만을 반환"}
//  ],
//  "temperature": 0.2,
//  "max_tokens" : 2000
//}

{  "model":"gpt-3.5-turbo",  "max_tokens":2000,  "temperature":0.2,  "messages":[    {"role":"user","content":"for test"},    {"role":"system","content":"내용에 대해 다음 네 가지 조건을 모두 만족하여 응답해주세요.\\n1. 스크립트를 문맥에 맞게 수정하기\\n2. 문맥을 수정한 스크립트에서 중요한 정보만을 요약하기\\n3. 요약된 내용이 한국어가 아니라면 한국어로 번역하기\\n4. 내용만을 반환"}]}